### ISSUE TITLE
Introduce a proper "Getting Started" section for absolute beginners.

### ISSUE THREAD

**Issue by Arzenar** [notpresident35/awesome-learn-gamedev#5]
I remember having an extremely hard time getting a foothold in graphical programming at all. So much math, concepts, programming paradigms and project design patterns that I felt downright overwhelmed and demotivated. Just a generic Unity tutorial alone has to explain so much to even show anything reasonable without even going into detail.

To live up to the "learn" part of the name of the repo, more time should be spent on giving resources for absolute beginners to learn more about general graphical programming (the math, rendering, interactivity), an extra section on the most basic basics should be added. Even for people who have years of experience can benefit from some lesser known basics.

I see that some very basic resources are already in here, but I would like to see them presented separately in an extra section so that there is no need to search for them for a long time (especially as this list will continue to grow). A structure that takes beginners and readers right by the hand.

I've picked out a few here that I had very good experiences with and learned a lot from:
- [TheCodingTrain](https://www.youtube.com/c/TheCodingTrain) (Dan Shiffman) is a very wholesome person who takes every programming beginner by hand with joy and verve, and programs small games and complex algorithms in an understandable way and nicely visualized.
- [CodingMath](https://www.youtube.com/user/codingmath) (Keith Peters) has a very beginner friendly and understandably written series on math for graphics programmers. It goes over many topics ans sort of gives a rough overview of what graphical programming is. While his series is over (unfortunately), these days he writes blog posts as [Bit101](http://www.bit-101.com/blog/) (he is also on github with the same name). It's important to watch his videos as he talks about verlet integration, tweening and easing in a very understandable way.
- [Freya Holmér](https://www.youtube.com/c/Acegikmo/videos) puts a big focus on shaders and interpolation in her videos. It's written entirely in Unity. She also provides many visualizations about trigonometry on her [Twitter](https://twitter.com/FreyaHolmer). If it's about some, actually known, trigonometric problem, she probably has a visualization of it, which explains it amazingly simple, on her Twitter. Her talk at the [IndiaGDC](https://www.youtube.com/watch?v=NzjF1pdlK7Y) is also worth watching 
- [AdamCYounis](https://www.youtube.com/c/AdamCYounis/videos) deals entirely with pixelart and pixelart algorithms in Unity. He's really good at pixelart and you learn an incredible amount just from watching him.

And here are two people who have a lot of essays about game design:
[Game Design Thinking](https://www.youtube.com/c/GameDesignThinking) and [Razbuten](https://www.youtube.com/c/razbuten/featured)

**Comment by dawdle-deer** [comment]
This resource list is intentionally categorized by role, not skill level, to increase awareness of the different disciplines and assist developers who are already familiar with the distinctions in finding resources for their role. However, a dedicated marker for resources aimed at new developers - similar to 🟪 for "important resource" - would be an improvement to this list. 

Graphics programming in particular is an expansive sub-category, and is not typically presented to new programmers due to that prerequisite knowledge. This is why the first link is the [Awesome Graphics repository](https://github.com/luisnts/awesome-computer-graphics), because that repository (even not specifically related to games) will be able to (and has already) arranged a better collection of resources related to graphics.

Additionally, math learning content would be a useful inclusion - I will put [Awesome Math](https://github.com/rossant/awesome-math) in the programming section for this purpose, and I will look over CodingMath and Bit101 - the second in particular seems valuable.

For beginner programmers, learning through a course that directs them to exactly what they need is a much faster, more effective, and less confusing way to learn to code than any video tutorial series. It may be less enticing, but I feel much more comfortable directing a new programmer to MIT open courseware, Udemy, OSSU, or a book like C# for Beginners than I would directing them to even a very good youtube series (which I'm sure TheCodingTrain is - I have seen several of his videos, and while they are a _tad_ patronizing for my taste, they seem useful enough to a brand-new programmer).

Freya Holmer's shader series is already included under Technical Art > Shaders. I've added her IndiaGDC talk to my youtube playlist and will add it to the main list eventually (this is due for reorganization anyway, since playlists abstract away all video content and sort it by addition date, not by role, but is partly intentional to avoid drawing focus on longer, slower-to-learn video content).

I will include AdamCYounis's [Pixel Art Class](https://www.youtube.com/watch?v=7BWr2tlK-4c&list=PLLdxW--S_0h4dlWUpl-TzBp-ulqK3NiM_) in the art section, with a recommendation for the rest of the channel.

I find that video essays on game design are helpful, but they are not the best way to learn, as they are bound by the social media space to be entertaining in ways that tend to hinder the educational value. Rare channels such as Extra Credits, Joseph Anderson (who is not included in this list, but is in the youtube playlist), and GMTK offer significant educational value while still being interesting, but no channel is an exception to this rule. To achieve its learning goal, the game design section focuses on books, classes, and reference material and avoids essays if possible. I will make note of this curation detail somewhere relevant.

**Comment by Arzenar** [comment]
Two more things regarding Freya Holmér: I'd also recommend to also take in her mathematics quadrology, as it's very beginner-friendly regarding trigonometry and furthermore tells useful things about dot-product (lines of sight of objects and their relations to each other), world-to-local-space and interpolation. She also includes challenges to program in Unity.

And I was talking about these visualizations on Twitter: [Dot Product](https://twitter.com/freyaholmer/status/1200807790580768768), [Cross Product 1](https://twitter.com/freyaholmer/status/1203059678705602562) and [Cross Product 2](https://twitter.com/freyaholmer/status/1203421083371749376).

Regarding game design essays: You should definitely watch a video of Game Design Thinking. I can guarantee you it's packed with psychological knowledge about player behaviour. These videos are truely stunning without going into social media or pure entertainment at all. It's a shame this channel is so small.

Also I forgot to mention to include Jorge Rodriguez series [Math for Game Developers](https://www.youtube.com/watch?v=sKCF8A3XGxQ&list=PLW3Zl3wyJwWOpdhYedlD-yCB7WQoHf-My).

**Comment by dawdle-deer** [comment]
Added blue star (💠) marker for "best for beginner" links.

Added Bit101, Awesome Math, and Pixel Art Class.

Will not include, TheCodingTrain, CodingMath, Game Design Thinking, Razbuten, and Math for Game Developers. Apologies, but I have watched a few videos from each channel (and am subscribed to Razbuten), and they don't quite fit here for various reasons. 

Updated About page to be more up-front about my curation standards.

Updated freya holmer's entry to include her math and tool dev series.
